INSERT INTO categories (name) VALUES ('Cars');
INSERT INTO categories (name) VALUES ('Misc');
INSERT INTO categories (name) VALUES ('Pets');
INSERT INTO categories (name) VALUES ('Furniture');
INSERT INTO categories (name) VALUES ('Electronics');
INSERT INTO categories (name) VALUES ('Real Estate');
INSERT INTO categories (name) VALUES ('Clothing');
INSERT INTO categories (name) VALUES ('Toys/Games');
INSERT INTO categories (name) VALUES ('Appliances');
INSERT INTO categories (name) VALUES ('Tools');
INSERT INTO categories (name) VALUES ('Sporting Goods');
INSERT INTO categories (name) VALUES ('Books');
